Repository puruagarwal1/python_dir, pull requests merged in 2023-10, with the labels that each got.

#2 added new python program.
  checkLeapYear.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#4 Create Fibonacci series
  Kotlin/Fibonacci series
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#5 Fixed hactoberfest 23 badge
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#7 Enhanced factorial recurssion.py
  factorial recurssion.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#8 Added euclid's algorithm
  euclideanAlgorithm.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#9 Cheat sheet for streamlit
  cheat sheet.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#10 Added Binary Search Algorithm
  binarySearch.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#12 Add timer decorator to measure execution time
  add-timer-decorator.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#16 Implementation of BFS and DFS added
  Python/Graphs/bfs.py
  Python/Graphs/dfs.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#17 Created selection_sort.py
  selection_sort.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#30 added kadanes algorithm
  kadanesAlgorithm.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#34 Implement Dijkstra's algorithm for finding shortest paths in a weight…
  Dijkstra's algorithm.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#14 Create linkedlist.py
  linkedlist.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#33 Merge sort algorithm
  breadth_first_search.py
  merge_sort.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#15 Create Stack.py
  Stack.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#19 Create Bubble_Sort.py
  Bubble_Sort.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#20 Added sorting and searching algorithms for kotlin, updated Fibonacci series program
  Kotlin/binarySearch.kt
  Kotlin/fibonacciSeries.kt
  Kotlin/insertionSort.kt
  Kotlin/linearSearch.kt
  Kotlin/selectionSort.kt
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#40 Added lowerBoundAndUpperBound.py
  lowerBoundAndUpperBound.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023

#21 Create even.py
  even.py
Labels: hacktoberfest-accepted, hacktoberfest accepted, hacktoberfest2023
